import { Inter } from "next/font/google";
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from "./theme.js"
// components

import Navbar from "./components/Navbar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme = {theme}>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
